spring:
  datasource:
    url: jdbc:mysql://47.102.37.165:3306/train?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: train2019gz
    password: train2019gzdHJhaW4yMDE5Z3o
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations:
  - classpath:/mappers/**/*.xml

  
logging:
  level:
    com.neusoft.ht.login.mapper: debug
    com.neusoft.ht.fee.mapper: debug
    
http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
      port: 8088

  

