server:
  port: 8888
  
spring:
  application:
    name: heatEurekaServer
    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8888/eureka